config/routes.rb
Resumonk::Application.routes.draw do
  resources :skills
  resources :experiences
  resources :educations
  resources :users do
    resources :resumes
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  match "/signup" => "users#new", as: :signup
  
  match "/login" => "sessions#new", as: :login
  match "/logout" => "sessions#destroy", as: :logout
  
  match "/toc" => "static_pages#toc", as: :toc
  match "/about" => "static_pages#about", as: :about
  match "/faq" => "static_pages#faq", as: :faq
  match "/privacy_policy" => "static_pages#privacy", as: :privacy
  match "/resume_templates" => "static_pages#resume_templates", as: :resume_templates
  match "users/:user_id/show_links/:id" => "resumes#show_links", as: :show_links
  match "users/:user_id/show_template/:id" => "resumes#show_template", as: :show_template
  put "users/:user_id/choose_template/:id" => "resumes#choose_template", as: :choose_template
  root to: "static_pages#home", as: :root
  
  get "/r/:short_link" => "resumes#short_link", as: :short_link_path
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  
  
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, format: { with: valid_email_regex }
  validates :email, uniqueness: true
  validates :password, length: { within: 6..50 }
  
  before_save :create_remember_token, :create_username
  
  def to_param
    "#{id}-#{username.gsub(/[^a-z0-9]+/i, '-')}"
  end
    
  # associations
  has_many :resumes
  
  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
    def create_username
      self.username = email.split('@')[0]
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_user, only: [:destroy]
  before_filter :signed_in_user, only: [:show]
  before_filter :correct_user, only: [:show]
  
  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
    @resumes = @user.resumes
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        
        format.html do
          sign_in @user
          flash[:success] = "Welcome to the Sample App!"
          redirect_to new_user_resume_path(current_user)
        end
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  
  private
      def correct_user
        user = User.find(params[:id])
        redirect_to root_path unless current_user?(user)
      end

      def admin_user
        redirect_to root_path unless current_user.admin?
      end
      
end

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: "nice eight columns right" }) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <h4>Signup</h4>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class: "expand input-text", placeholder: "john@doe.com" %>
  </div>
  
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: "expand input-text", placeholder: "Secret password" %>
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation, "Please enter your password again." %>
    <%= f.password_field :password_confirmation, class: "expand input-text", placeholder: "Secret password" %>
  </div>
  
  <div class="action">
    <%= link_to "Already have an account? Login now.", login_path, class: "five columns left"%>
    <%= f.submit "Signup", class: "btn right" %>
  </div>
  
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="eight columns offset-by-two login_box">
    <div class="monk three columns">
      <%= image_tag("monk.png") %>
    </div>
    
    <%= render 'form' %>
    
  </div><!--ten columns-->
</div><!--row-->

app/views/users/show.html.erb
<section class="dashboard">
  <div class="row">
  <div class="ten columns offset-by-one">
    <div class="panel clearfix">
      <div class="seven columns">
        <h4>Howdy, <%= @user.username.humanize %> </h4>
        <p>You currently have <%= pluralize(@user.resumes.count, "resume") %> active resumes.</p>
      </div>
      
      <%= link_to "Create a new resume", new_user_resume_path(current_user), class: "button big radius nice right" %>
    </div><!--panel-->
   </div><!-- ten columns-->
   </div><!--row-->
   
    <% if @resumes.any? %>
      <div class="row">
      <table class="ten columns centered">
        <% @resumes.each do |resume| %>
          <tr>
            <td class="first">
              <h3><%= resume.title.nil? ? "Resume title" : resume.title %></h3>
              <strong>Unique URL: </strong><%= link_to "http://resumonk.com/r/#{resume.short_link}", "http://resumonk.com/r/#{resume.short_link}", target: "_blank" %>
            </td>
            
            <td><%= link_to 'View', [current_user, resume], class: "button small white radius" %></td>
            <td><%= link_to "Save as PDF", user_resume_path(current_user, resume, format: "pdf"), class: "button small green radius"  %></td>
            <td><%= link_to 'Edit', edit_user_resume_path(current_user, resume), class: "button small blue radius" %></td>
            <td><%= link_to 'Destroy', [current_user, resume], confirm: 'Are you sure?', method: :delete, class: "button radius red small" %></td>
          </tr>
        <% end %>
      </table>
      </div><!--row-->
    <% else %>
      <div class="row">
      <table class="ten columns centered">
          <tr>
            <td>
              <h3 style="text-align:center;">You haven't created any resumes yet. Go ahead, <%= link_to "get started!", new_user_resume_path(current_user) %></h3>
            </td>
          </tr>
      </table>
      </div>
    <% end %>
    
    <div class="row break">
      <div class="ten columns additional_info centered clearfix">
        <div class="six columns donation_box ">
          <h4>Donate $10, $20 or $50!</h4>
          <p>Resumonk has cost me a lot of hours of work, if you use it, please donate a token of your appreciation!</p>
           <a href="#" class="four columns button green radius">Donate</a>
        </div><!--donation-box-->
      
        <div class="jobs five columns">
          <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
          <script type="IN/JYMBII" data-format="inline"></script>
        </div>
      </div><!--ten columns-->
    </div><!--row-->
    
 
</section><!--dashboard-->