config/routes.rb
Resumonk::Application.routes.draw do
  resources :skills
  resources :experiences
  resources :educations
  resources :users do
    resources :resumes
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  match "/signup" => "users#new", as: :signup
  
  match "/login" => "sessions#new", as: :login
  match "/logout" => "sessions#destroy", as: :logout
  
  match "/toc" => "static_pages#toc", as: :toc
  match "/about" => "static_pages#about", as: :about
  match "/faq" => "static_pages#faq", as: :faq
  match "/privacy_policy" => "static_pages#privacy", as: :privacy
  match "/resume_templates" => "static_pages#resume_templates", as: :resume_templates
  match "users/:user_id/show_links/:id" => "resumes#show_links", as: :show_links
  match "users/:user_id/show_template/:id" => "resumes#show_template", as: :show_template
  put "users/:user_id/choose_template/:id" => "resumes#choose_template", as: :choose_template
  root to: "static_pages#home", as: :root
  
  get "/r/:short_link" => "resumes#short_link", as: :short_link_path
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoudCV - Online Resume Builder - Create a beautiful and professional Resume in minutes</title>
  <meta name="author" content="Bharani M" />
<meta name="keywords" content="Resume, CV, resume builder, online resume generator, creative resume, online CV builder, professional resume, beautiful resume designs, online resume builder, create beautiful resumes online, desiger resumes, simple resume online, PDF resume">
<meta name="description" content="LoudCV is an online resume builder that saves you money and time by helping you create professional and beautiful resumes. LoudCV handles the job of formatting and converting your resume into pdf format, thereby letting you focus on writing quality content.">

<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => "screen" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "morphext" %>
  <%= javascript_include_tag "morphext" %>
  <%= favicon_link_tag "favicon.png" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-31001901-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
  <div id="header_border"></div>
  
  <header class="container">
    <div class="row">
      <div class="ten columns offset-by-one">
      <h1 class="four columns" id="logo"><%= link_to "", root_path %></h1>
    
      <nav class="eight columns">
        <% if signed_in? %>
          <ul class="top_nav right">
            <li><%= link_to "Your Resumes", current_user, class: "main" %></li>
            <li><%= link_to "Sign out", logout_path, class: "main" %></li>
          </ul><!-- top_nav-->
        <% else %>
          <ul class="single right">
            <span class="completely_free">Go ahead, it completely free!</span>
            <li class="single_link login"><%= link_to "Login", login_path %></li>
            <li class="single_link signup"><%= link_to "Sign Up", signup_path %></li>
          </ul>
        <% end %>
        
      </nav>
      </div><!--ten columns-->
    </div><!-- row-->
  </header><!-- container-->
  
  <section class="container body_content">
    <!-- alerts -->
    <% flash.each do |key, value| %>
      <div class="row">
        <div id="alert" class=" eight columns centered alert-box <%= key %>"><%= value %></div>
      </div><!--row-->
    <% end %>
    
    <%= yield %>
  </section><!--container-->
  
  
  <footer>
    <div class="container">
      <div class="row">
        <div class="ten columns offset-by-one">
          <p class="copyright four columns">&copy; <span title="LoudCV - Online resume builder">LoudCV</span>. All Rights Reserved.</p>
          <ul class="sitemap right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Conditions", toc_path %></li>
            <li><%= link_to "Privacy Policy", privacy_path %></li>
            <li><%= link_to "FAQ", faq_path %></li>
            <li><%= link_to "Resume Templates", resume_templates_path %></li>
          </ul>
        </div><!--ten columns-->
       </div><!--row-->
      </div><!-- container-->
  </footer>
</body>
</html>

app/views/layouts/classica.html.erb
<!--
  The woods are lovely, dark, and deep,
  But I have promises to keep,
  And miles to go before I sleep,
  And miles to go before I sleep.
  ~ Robert Frost
-->

<!DOCTYPE html>
<html>
<head>
  <title><%= @resume.user.username.humanize %>'s Resume | Powered by Resumonk - Online Resume Builder</title>
  <meta name="author" content="Bharani M" />
	<meta name="keywords" content="Resume, CV, resume builder, online resume generator, creative resume, online CV builder, professional resume, beautiful resume designs, online resume builder, create beautiful resumes online, desiger resumes, simple resume online, PDF resume">
	<meta name="description" content="">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "classica_pdf", "show_page" %>
  <%= csrf_meta_tags %>

</head>
  <body class="classica">
    
    <%= render "show_page_header" %>
    
    
    <div class="show_container">
        <div id="container">
          <div class="container_inner">
          <div class="wrapper clearfix">
          <div id="about" class="clearfix">
            <h1><%= "#{@resume.firstname} #{@resume.lastname}" %></h1>
            <% unless @resume.experiences.first.designation.blank? %>
              <h2><%= @resume.experiences.first.designation %></h2>
            <% end %>
         </div><!--about-->

         <div class="row clearfix"> 
          <% unless @resume.objective.blank? %>
          <div class="objective">

                <p><%= @resume.objective %></p>

          </div><!--objective-->
              <% end %>

          <ul id="contact">
            <% unless @resume.phone.blank? %>
              <li><span>Mobile</span><strong><%= @resume.phone %></strong></li>
            <% end %>
            <li><span>Email</span><strong><a class="email" href='mailto:<%= "#{@resume.user.email}" %>'><%= @resume.user.email %></a></strong></li>
            <li><span>Address</span><strong><%= @resume.address %></strong></li>

            <% unless @resume.website.blank? %>
              <li><span>Website</span><strong><%= link_to @resume.website, @resume.website %></strong></li>
            <% end %>



          </ul><!--contact-->
          </div><!--clearfix-->
        </div><!--wrapper-->

          <div id="content">
            <div class="section">
                <div class="section_header">
                  <span>Education</span>
                </div><!--section-header-->
              <% @resume.educations.each_with_index do |education, index| %>
                <div class="item">
                  <h3><%= education.institute_name %></h3>
                  <h4><%= education.degree %></h4>
                  <div class="date"><%= education.start_date %> to <%= education.end_date %></div>
                  <% unless education.description.blank? %>
                    <div class="description">
                      <p><%= education.description %></p>
                    </div>
                  <% end %>
                </div>
              <% end %>
          </div><!--section-->

          <div class="section">
            <div class="section_header">
              <span>Experience</span>
            </div><!--section-header-->

          <% @resume.experiences.each_with_index do |experience, index| %>
            <div class="item">
              <h3><%= experience.company_name %></h3>
              <h4><%= experience.designation %></h4>
              <div class="date"><%= experience.start_date %> to <%= experience.end_date %></div>
              <div class="description">
                <p><%= experience.job_description %></p>
              </div>
            </div>
          <% end %>
        </div><!--section-->


      </div><!--content-->

      <div class="sidebar">

          <% if @resume.skills.any? %>
            <div class="section skills">
                <div class="section_header">

                  <span>Skills</span>
                </div><!--section-header-->
            <% @resume.skills.each do |skill| %>
               <div class="item">
                  <h3 class="skill_header"><%= skill.skill %></h3>
                    <% unless skill.description.blank? %>
                      <div class="description">
                        <h4><%= skill.description %></h4>
                      </div>
                    <% end %>
                </div>
            <% end %>
          </div><!--skills-->
          <% end %>

        </div><!--sidebar-->
        </div><!--container_inner-->
        </div><!--container-->
    </div>
    
  </body>
</html>

app/views/layouts/elegant.html.erb
<!--
  The woods are lovely, dark, and deep,
  But I have promises to keep,
  And miles to go before I sleep,
  And miles to go before I sleep.
  ~ Robert Frost
-->

<!DOCTYPE html>
<html>
<head>
  <title><%= @resume.user.username.humanize %>'s Resume | Powered by Resumonk - Online Resume Builder</title>
  <meta name="author" content="Bharani M" />
	<meta name="keywords" content="Resume, CV, resume builder, online resume generator, creative resume, online CV builder, professional resume, beautiful resume designs, online resume builder, create beautiful resumes online, desiger resumes, simple resume online, PDF resume">
	<meta name="description" content="">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "basic_pdf", "show_page" %>
  <%= csrf_meta_tags %>

</head>
  <body class="elegant">
    
    <%= render "show_page_header" %>
    
    
    <div class="show_container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/prestige.html.erb
<!--
  The woods are lovely, dark, and deep,
  But I have promises to keep,
  And miles to go before I sleep,
  And miles to go before I sleep.
  ~ Robert Frost
-->

<!DOCTYPE html>
<html>
<head>
  <title><%= @resume.user.username.humanize %>'s Resume | Powered by Resumonk - Online Resume Builder</title>
  <meta name="author" content="Bharani M" />
	<meta name="keywords" content="Resume, CV, resume builder, online resume generator, creative resume, online CV builder, professional resume, beautiful resume designs, online resume builder, create beautiful resumes online, desiger resumes, simple resume online, PDF resume">
	<meta name="description" content="">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "prestige_pdf", "show_page" %>
  <%= csrf_meta_tags %>

</head>
  <body class="prestige">
    
    <%= render "show_page_header" %>
    
    
    <div class="show_container">
       <div id="container">

          <div class="wrapper clearfix">
          <div id="about">
            <h1><%= "#{@resume.firstname} #{@resume.lastname}" %></h1>
            <% unless @resume.experiences.first.designation.blank? %>
              <h2><%= @resume.experiences.first.designation %></h2>
            <% end %>
          </div><!--about-->

          <ul id="contact">
            <p id="contact_header">Contact Info</p>
            <% unless @resume.phone.blank? %>
              <li><span>Mobile</span><strong><%= @resume.phone %></strong></li>
            <% end %>
            <li><span>Email</span><strong><a class="email" href='mailto:<%= "#{@resume.user.email}" %>'><%= @resume.user.email %></a></strong></li>
            <li><span>Address</span><strong><%= @resume.address %></strong></li>

            <% unless @resume.website.blank? %>
              <li><span>Website</span><strong><%= link_to @resume.website, @resume.website %></strong></li>
            <% end %>



          </ul><!--contact-->
        </div><!--wrapper-->

          <div id="content">
            <div class="section">
                <div class="section_header">
                  <span>Education</span>
                </div><!--section-header-->
              <% @resume.educations.each_with_index do |education, index| %>
                <div class="item">
                  <h3><%= education.institute_name %></h3>
                  <h4><%= education.degree %></h4>
                  <div class="date"><%= education.start_date %> to <%= education.end_date %></div>
                  <% unless education.description.blank? %>
                    <div class="description">
                      <p><%= education.description %></p>
                    </div>
                  <% end %>
                  <% unless index == (@resume.educations.length - 1) %>
                    <%= image_tag 'pdf/prestige_dots.jpg', class:"dots"  %>
                  <% end %>
                </div>
              <% end %>
          </div><!--section-->

          <div class="section">
            <div class="section_header">
              <span>Experience</span>
            </div><!--section-header-->

          <% @resume.experiences.each_with_index do |experience, index| %>
            <div class="item">
              <h3><%= experience.company_name %></h3>
              <h4><%= experience.designation %></h4>
              <div class="date"><%= experience.start_date %> to <%= experience.end_date %></div>
              <div class="description">
                <p><%= experience.job_description %></p>
              </div>
              <% unless index == (@resume.experiences.length - 1) %>
                <%= image_tag 'pdf/prestige_dots.jpg', class:"dots"  %>
              <% end %>
            </div>
          <% end %>
        </div><!--section-->
      </div><!--content-->

      <div class="sidebar">
         <% unless @resume.objective.blank? %>
        <div class="objective">
          <div class="section">
              <div class="section_header">
                <span>Professional Profile</span>
              </div><!--section-header-->

              <p><%= @resume.objective %></p>
          </div><!--section-->
        </div><!--objective-->
            <% end %>
          <% if @resume.skills.any? %>
            <div class="section skills">
                <div class="section_header">

                  <span>Skills</span>
                </div><!--section-header-->
            <% @resume.skills.each do |skill| %>
               <div class="item">
                  <h3 class="skill_header"><%= skill.skill %></h3>
                    <% unless skill.description.blank? %>
                      <div class="description">
                        <h4><%= skill.description %></h4>
                      </div>
                    <% end %>
                </div>
            <% end %>
          </div><!--skills-->
          <% end %>

        </div><!--sidebar-->
        </div><!--container-->
    </div>
    
  </body>
</html>

app/views/layouts/simplimo.html.erb
<!--
  The woods are lovely, dark, and deep,
  But I have promises to keep,
  And miles to go before I sleep,
  And miles to go before I sleep.
  ~ Robert Frost
-->

<!DOCTYPE html>
<html>
<head>
  <title><%= @resume.user.username.humanize %>'s Resume | Powered by Resumonk - Online Resume Builder</title>
  <meta name="author" content="Bharani M" />
	<meta name="keywords" content="Resume, CV, resume builder, online resume generator, creative resume, online CV builder, professional resume, beautiful resume designs, online resume builder, create beautiful resumes online, desiger resumes, simple resume online, PDF resume">
	<meta name="description" content="">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "simplimo_pdf", "show_page" %>
  <%= csrf_meta_tags %>

</head>
  <body class="simplimo">
    
    <%= render "show_page_header" %>
    
    
    <div class="show_container">
       <div id="page-wrap">
          <div id="contact-info" class="vcard clearfix">

              <!-- Microformats! -->

              <h1 class="fn"><%= "#{@resume.firstname} #{@resume.lastname}" %></h1>

              <p class="info">
                <% unless @resume.phone.blank? %>
                  Cell: <span class="tel"><%= @resume.phone %></span><br />
                <% end %>
                  Address: <span class="add"><%= @resume.address %></span><br />
                  Email: <a class="email" href='mailto:<%= "#{@resume.user.email}" %>'><%= @resume.user.email %></a><br />
                <% unless @resume.website.blank? %>
                  Website: <%= link_to @resume.website, @resume.website %></a>
                <% end %>
              </p>

          </div>

          <% unless @resume.objective.blank? %>
            <div id="objective">
              <p>
                 <%= @resume.objective %>
              </p>
            </div>
          <% end %>
          <div class="clear"></div>

          <dl>
              <dd class="clear"></dd>

              <dt>Education</dt>

              <% @resume.educations.each do |education| %>
               <dd class="full">
                    <h2><%= education.institute_name %>
                        <span class="timespan"><%= education.start_date %> to <%= education.end_date %></span>
                    </h2>

                    <p><strong><%= education.degree %>

                      </strong><br />
                    <% unless education.description.blank? %>
                      <div class="description">
                        <p><%= education.description %></p>
                      </div>
                    <% end %>
                  </p>
                </dd>
              <% end %>


              <dd class="clear" style=" page-break-before:auto"></dd>
                    <dd class="clear"></dd>

                    <dt>Experience</dt>

                    <% @resume.experiences.each do |experience| %>
                     <dd class="full">
                          <h2><%= experience.designation %>
                              <span class="timespan"><%= experience.start_date %> to <%= experience.end_date %></span>
                          </h2>

                          <p><strong><%= experience.company_name %></strong><br />
                          <p class="description"><%= experience.job_description %></p>
                      </dd>
                    <% end %>


            <dd class="clear" style="margin-bottom: 10px; page-break-before:auto"></dd>

              <% if @resume.skills.any? %>
                <dt>Skills</dt>
                <% @resume.skills.each do |skill| %>
                  <dd class="full">
                    <h2><%= skill.skill %></h2>
                    <p><%= skill.description %></p>
                  </dd>
                  <% end %>
              <% end %>


          </dl>

          <div class="clear"></div>
        </div><!--page-wrap-->
    </div>
    
  </body>
</html>

app/views/layouts/sleek.html.erb
<!--
  The woods are lovely, dark, and deep,
  But I have promises to keep,
  And miles to go before I sleep,
  And miles to go before I sleep.
  ~ Robert Frost
-->

<!DOCTYPE html>
<html>
<head>
  <title><%= @resume.user.username.humanize %>'s Resume | Powered by Resumonk - Online Resume Builder</title>
  <meta name="author" content="Bharani M" />
	<meta name="keywords" content="Resume, CV, resume builder, online resume generator, creative resume, online CV builder, professional resume, beautiful resume designs, online resume builder, create beautiful resumes online, desiger resumes, simple resume online, PDF resume">
	<meta name="description" content="">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "sleek_pdf", "show_page" %>
  <%= csrf_meta_tags %>

</head>
  <body class="sleek">
    
    <%= render "show_page_header" %>
    
    
    <div class="show_container">
       <div id="container">

          <div id="about">
            <h1><%= "#{@resume.firstname} #{@resume.lastname}" %></h1>
            <% unless @resume.experiences.first.designation.blank? %>
              <h2><%= @resume.experiences.first.designation %></h2>
            <% end %>
          </div><!--about-->

          <ul id="contact">
            <% unless @resume.phone.blank? %>
              <li><span>Mobile</span> <%= @resume.phone %></li>
            <% end %>
            <li><span>Email</span><a class="email" href='mailto:<%= "#{@resume.user.email}" %>'><%= @resume.user.email %></a></li>
            <li><span>Address</span><%= @resume.address %></li>

            <% unless @resume.website.blank? %>
              <li><span>Website</span><%= link_to @resume.website, @resume.website %></li>
            <% end %>



          </ul><!--contact-->


          <div id="content">
            <div class="section">
                <div class="section_header">
                  <%= image_tag 'pdf/dot.jpg', class:"dot" %>
                  <span>Education</span>
                </div><!--section-header-->
              <% @resume.educations.each do |education| %>
                <div class="item">
                  <h3><%= education.institute_name %></h3>
                  <h4><%= education.degree %></h4>
                  <div class="date"><%= education.start_date %> to <%= education.end_date %></div>
                  <% unless education.description.blank? %>
                    <div class="description">
                      <p><%= education.description %></p>
                    </div>
                  <% end %>
                </div>
              <% end %>
          </div><!--section-->

          <div class="section">
            <div class="section_header">
              <%= image_tag 'pdf/dot.jpg', class:"dot" %>
              <span>Experience</span>
            </div><!--section-header-->

          <% @resume.experiences.each do |experience| %>
            <div class="item">
              <h3><%= experience.company_name %></h3>
              <h4><%= experience.designation %></h4>
              <div class="date"><%= experience.start_date %> to <%= experience.end_date %></div>
              <div class="description">
                <p><%= experience.job_description %></p>
              </div>
            </div>
          <% end %>
        </div><!--section-->
      </div><!--content-->

      <div class="sidebar">
         <% unless @resume.objective.blank? %>
        <div class="objective">
          <div class="section">
              <div class="section_header">
                <%= image_tag 'pdf/dot.jpg', class:"dot" %>
                <span>Professional Profile</span>
              </div><!--section-header-->

              <p><%= @resume.objective %></p>

        </div><!--objective-->
            <% end %>
          <% if @resume.skills.any? %>
            <div class="section skills">
                <div class="section_header">
                  <%= image_tag 'pdf/dot.jpg', class:"dot" %>
                  <span>Skills</span>
                </div><!--section-header-->
            <% @resume.skills.each do |skill| %>
               <div class="item">
                  <h3 class="skill_header"><%= skill.skill %></h3>
                    <% unless skill.description.blank? %>
                      <div class="description">
                        <h4><%= skill.description %></h4>
                      </div>
                    <% end %>
                </div>
            <% end %>
          </div><!--skills-->
          <% end %>

        </div><!--sidebar-->
        </div><!--container-->
    </div>
    
  </body>
</html>